account/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views
from django.contrib.auth import views as _

app_name = 'account'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateUserEmailView.as_view(), name='activate'),
    path('active/again', views.SendEmailConfirmationLinkAgain.as_view(), name="active-again"),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('update/<int:pk>/', views.UpdateUserProfileView.as_view(), name='update'),
    path('delete/', views.ajax_delete_user, name='delete'),
    path('users/', views.AdministratorUsersManagerView.as_view(), name='users'),
    path('user/contacts/', views.ContactsView.as_view(), name='contacts'),
    path('dashboard/search/', views.DashboardSearchView.as_view(), name='dashboard-search'),
    path('administrator/website/system/chart/', views.ChartSystem.as_view(), name='chart'),
    path('ajax/validator/username', views.validate_username, name='validator-username'),
    path('ajax/validator/email', views.validate_email, name='validator-email'),
    path('ajax/validators/slug', views.ajax_slug_validators, name='aj-sl-val'),
    path('ajax/notification/read', views.notification_read_ajax, name='notif-read'),
    path('ajax/passwords/match', views.login_password_matches, name='validator-ps'),
    path('ajax/author/req', views.ajax_author_req, name='author-req'),
    path('contact/create/', views.CreateContactView.as_view(), name='contact-create'),
    path('contact/update/<int:pk>/', views.UpdateContactView.as_view(), name='contact-update'),
    path('contact/delete/', views.ajax_delete_user_contact, name='contact-delete'),
    path('article/create/', views.CreateArticleView.as_view(), name='article-create'),
    path('article/update/<int:pk>/', views.UpdateArticleView.as_view(), name='article-update'),
    path('article/delete/', views.ajax_delete_article, name='article-delete'),
    path('article/preview/<int:pk>/', views.DetailArticlePreView.as_view(), name='article-preview'),
    path('articles/', views.ListArticleView.as_view(), name='articles'),
    path('article/wrote/<int:pk>/', views.article_wrote, name='article-wrote'),
    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('categories/', views.CategoryAdminManagement.as_view(), name='categories'),
    path('category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category-update'),
    path('category/delete/', views.ajax_delete_category, name='category-delete'),
    path('notif/create/', views.NotificationCreator.as_view(), name='notif-create'),
    path('notifs/manage/', views.AllNotifications.as_view(), name='notifs-admin'),
    path('notif/delete/', views.ajax_delete_notifs, name="notif-delete"),
    path('message/create/', views.CreateMessage.as_view(), name="message-create"),
    path('messages/', views.MyMessages.as_view(), name='messages'),
    path('message/delete/', views.ajax_delete_messages, name='message-delete'),
    path('message/detail/<int:pk>/', views.MessageDetail.as_view(), name='message-detail'),
    path('message/update/<int:pk>/', views.MessageUpdate.as_view(), name="message-update"),
    path('comments/manage/', views.CommentManagement.as_view(), name='comments'),
    path('comments/publish/<int:pk>/', views.CommentPublisher.as_view(), name="comment-update"),
    path('comments/delete/', views.ajax_delete_comment, name='comment-delete'),
    path('user/creation/', views.AdminUserCreation.as_view(), name='user-create'),
    path('challenge/create/', views.CreateChallengeView.as_view(), name='challenge-create'),
    path('challenge/update/<int:pk>/', views.UpdateChallengeView.as_view(), name='challenge-update'),
    path('challenge/delete/', views.ajax_delete_challenges, name='challenge-delete'),
    path('challenges/', views.ChallengesView.as_view(), name='challenges'),
    path('views/', views.ViewsDetailPage.as_view(), name='views'),
    path('views/delete/', views.ajax_delete_view, name='view-delete'),
    path('views/likes/', views.LikedArticles.as_view(), name="article-likes"),
    path('article/like/delete/', views.ajax_delete_like, name='article-like-delete'),
] 

urlpatterns += [
    path('password_change/', _.PasswordChangeView.as_view(
        template_name='auth/registration/password_change.html',
        success_url=reverse_lazy('account:password_change_done')),
        name='password_change'),

    path('password_change/done/', _.PasswordChangeDoneView.as_view(
        template_name='auth/registration/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', _.PasswordResetView.as_view(
        template_name='auth/registration/password_reset.html',
        success_url=reverse_lazy('account:password_reset_done')),
        name='password_reset'),

    path('password_reset/done/', _.PasswordResetDoneView.as_view(
        template_name='auth/registration/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', _.PasswordResetConfirmView.as_view(
        template_name='auth/registration/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete')),
        name='password_reset_confirm'),

    path('reset/done/', _.PasswordResetCompleteView.as_view(
        template_name='auth/registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('authors/profiles/', views.ViewAuthorProfiles.as_view(), name='authors'),
    path('author/profile/<str:slug>/', views.ViewProfile.as_view(), name='author'),
    path('', views.HomePageView.as_view(), name='home'),
    path('posts/list/', views.ArticleListView.as_view(), name='posts'),
    path('post/detail/<str:slug>/', views.ArticleDetailView.as_view(), name='detail'),
    path('post/search/', views.SearchPageView.as_view(), name='search'),
    path('posts/category/<str:slug>/', views.CategoryRelatedToAnArticleView.as_view(), name='article-related-category'),
    path('about/', views.AboutUsPage.as_view(), name='about'),
    path('contact/', views.ContactUsPage.as_view(), name="contact"),
    path('ajax/like', views.liker, name="like"),
    path('ajax/like/update', views.send_likes_count_ajax, name="likeupdate"),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
    path('markdownx/', include( 'markdownx.urls')),
]

blog/models.py
from django.utils.html import format_html
from django.core.exceptions import ValidationError
from django.db import models
from os.path import splitext
from django.urls import reverse
from django.conf import settings
from extensions.converter import convert_to_jalali
from extensions.bot_send_to_channel import send_to_channel
from markdownx.models import MarkdownxField

User = settings.AUTH_USER_MODEL

COLOR_CHOICES = (
    ("danger", "قرمز"),
    ("primary", "آبی"),
    ("warning", "زرد"),
    ("success", "سبز"),
    ("dark", "تیره"),
)
STATUS = (
    ('d', 'پیش نویس'),
    ('p', 'منتشر شده'),
    ('i', 'در انتظار'),
    ('b', 'برگشت داده شده'),
)


def upload_images(instance, filename):
    return "articles/{}/%Y/%m/%d/{}".format(instance.author.username, filename)


def upload_video_validator(value):
    valid_extension = ['.wav', '.mp4', '.avi', '.mkv']
    ext = splitext(value)[1]
    if ext.lower() not in valid_extension:
        raise ValidationError("فرمت فایل پشتیبانی نمیشود!")


# Create your models here.
class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="liked_posts")
    post = models.ForeignKey('Article', on_delete=models.CASCADE, related_name="likes")

    def __str__(self) -> str:
        return "%s liked %s" % (self.user.username, self.post.title)

    def liker(self):
        return self.user.username


class Category(models.Model):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='child', verbose_name="دسته بالاتر")
    title = models.CharField(max_length=30, verbose_name="عنوان")
    slug = models.SlugField(max_length=30, unique=True, verbose_name="اسلاگ")
    color = models.CharField(max_length=100, choices=COLOR_CHOICES)
    desc = models.TextField(max_length=300, verbose_name="توضیحات", null=True, blank=True)
    date_cr = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ انتشار")
    date_up = models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش")

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article-related-category', kwargs={'slug':self.slug})

    def get_parents(self):
        full_path = [self.title]                  
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' -> '.join(full_path[::-1])

    def jdate_cr(self):
        return convert_to_jalali(self.date_cr)

    def jdate_up(self):
        return convert_to_jalali(self.date_up)


class ViewsMid(models.Model):
    ip_addr = models.GenericIPAddressField()
    ua = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.ip_addr
    
    def jdate(self):
        return convert_to_jalali(self.date)

class ArticleHit(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    ip_address = models.ForeignKey(ViewsMid, on_delete=models.CASCADE)
    date_cr = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.article.title

    def jdate_cr(self):
        return convert_to_jalali(self.date_cr)


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length=30, unique=True, verbose_name="اسلاگ مقاله")
    image = models.ImageField(upload_to=upload_images, verbose_name="تصویر مقاله")
    video = models.FileField(upload_to=upload_images, validators=[upload_video_validator], null=True, blank=True,
                             verbose_name='ویدئو مقاله',
                             help_text="""توجه داشته باشید که شما فقط میتونید یک محتوای ویدئویی یا محتوای
                              تصویری برای مقاله اتون آپلود کنید، بنابراین اگر فقط محتوای ویدئویی برای اپلود
                              نیاز دارید؛ تصویری که برایش انتخاب میکنید به عنوان آن پستر نمایش داده میشود""")
    text = MarkdownxField(verbose_name="متن مقاله",max_length=15000)
    category = models.ManyToManyField(Category, verbose_name="دسته بندی مقاله")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=" نویسنده مقاله")
    login_required = models.BooleanField(default=False, verbose_name="ثبت نام الزامی",
                                         help_text="اگر این گزینه فعال باشد کاربر باید ثبت نام کند تا پست شما را ببیند")
    date_cr = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ نوشته شدن مقاله")
    date_up = models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش مقاله")
    published = models.CharField(choices=STATUS, max_length=10, verbose_name="وضعیت انتشار مقاله")
    hits = models.ManyToManyField(ViewsMid, through=ArticleHit, related_name='hits',
                                  blank=True, verbose_name="تعداد بازدیدهای مقاله")
    back_description = models.TextField(max_length=300, null=True,
                                        blank=True, verbose_name="دلایل برگشت داده شدن مقاله",
                                        help_text="این بخش توسط ادمین نوشته میشود اگر پست شما دارای مشکلاتی باشد")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def get_categories(self):
        l1 = []
        l2 = []
        l3 = []
        l4 = []
        l5 = []
        for i in self.category.all():
            l1.append(i.title)
            if i.child.all():
                l2.append(i.title)
                for i in i.child.all():
                    l3.append(i.title)
                    if i.child.all():
                        l4.append(i.title)
                        for i in i.child.all():
                            l5.append(i.title)
        if l1:
            return "".join(l1)
        elif l1 and l2:
            return "{}>{}".format("".join(l1), "".join(l2))
        elif l1 and l2 and l3:
            return "{}>{}>{}".format("".join(l1), "".join(l2), "".join(l3))
        elif l1 and l2 and l3 and l4:
            return "{}>{}>{}".format("".join(l1), "".join(l2), "".join(l3), "".join(l4))
        elif l1 and l2 and l3 and l4 and l5:
            return "{}>{}>{}".format("".join(l1), "".join(l2), "".join(l3), "".join(l4), "".join(l5))

    def get_author(self):
        return self.author.username

    def image_tag(self):
        if self.image and self.video:
            return format_html(u"<video height='60' controls poster='{}'><source src='{}'></video>".format(
                self.image.url, self.video.url))
        elif self.image:
            return format_html("<img src={} height='60'>".format(self.image.url))

    def jdate_cr(self):
        return convert_to_jalali(self.date_cr)

    def jdate_up(self):
        return convert_to_jalali(self.date_up)

    def send_to_channel_f(self):
        if self.published == 'p':
            return send_to_channel(self.title, self.image.url, self.text, self.get_absolute_url())


class Comment(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="از طرف")
    to_article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="به مقاله", related_name="comments")
    title = models.CharField(max_length=50, verbose_name="عنوان")
    text = models.TextField(max_length=500, verbose_name="متن")
    published = models.BooleanField(default=False, verbose_name="منتشر شده")
    date_cr = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ انتشار")
    backed_description = models.TextField(max_length=500, null=True, blank=True)

    def __str__(self) -> str:
        return self.title

    def jdate_cr(self):
        return convert_to_jalali(self.date_cr)

blog/forms.py
from .models import Comment
from django import forms


class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'title',
            'text',
        ]

blog/templates/503.html
<h1>503 Server Unrechable</h1>
<p>It seems you wanna say I am down! am I down really? Oh no what I have become!.</p>

blog/templates/article.html
{% extends 'base_blog/base.html' %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<style>
#header.header-transparent {
    background: #1e4356 !important;
}

    .breadcrumbs ol li + li::before {
    display: inline-block;
    padding-right: 10px;
    padding-left: 10px;
    color: #6c757d;
    content: " / ";
}
.alert-dismissible .btn-close {
    position: absolute;
    top: 0;
    float: left;
    left: 0;
    z-index: 2;
    /* padding: 1.25rem 1rem; */
}
</style>


<script>
function getCookie(name) {
  let cookieValue = null;
  if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
          const cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
          }
      }
  }
  return cookieValue;
}
    


  // function Like(){
    // console.log("Starting...")
    // if ($("#ls").hasClass("like")){
      // $("#ls").removeClass("like").addClass("like-active")
    // }
    // else{
      // $("#ls").removeClass("like-active").addClass("like")
    // }
  // }


function getNewInfoAboutLike(){
  $.ajax({
    type: "POST",
    url: "{% url 'blog:likeupdate' %}",
    headers: {
      "X-CSRFToken": getCookie("csrftoken")
    },
    data: {"wal": "{{article.pk}}"},
    success: function(response){
      var likes = response.likes
      $("#like").text(`Likes ${likes}`)
    }
  })
}


$(document).ready(
  ()=>{
    if ($("#ls").length == 0){
      $(".tags").after('<div style="float: left;margin-right: auto;"><i onclick="Like()" class="far fa-heart"></i></div>')
    }
  }
)


function Like(){
  {% if not request.user.is_authenticated %}
  $("#null").html('<div class="alert alert-danger" role="alert">برای لایک کردن اول باید ثبت نام کنی! <a href=\'{% url "account:register" %}\'>ثبت نام</a></div>')
  $(document).scrollTop(0);
  {% else %}


  $.ajax({
    type: "POST",
    url: "{% url 'blog:like' %}",
    headers: {
      "X-CSRFToken": getCookie("csrftoken")
    },
    data: {"id": "{{article.pk}}"},
    success: function(response){
      console.log(response)
      if (response.liked){
        $("#ls").removeClass("far fa-heart").addClass("fas fa-heart")
        $("#null").html('<div class="alert alert-success alert-dismissible fade show" role="alert"><strong>{{request.user.username}}</strong> شما این مقاله رو لایک کردی؛ از شما ممنونیم و میتوانید مقالات لایک شده خود را در داشبورد پیدا کنید.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>')
        $(document).scrollTop(0)
        getNewInfoAboutLike()
      } 
      else if (response.disliked){
        $("#ls").removeClass("fas fa-heart").addClass("far fa-heart")
        $("#null").html('<div class="alert alert-danger alert-dismissible fade show" role="alert"><strong>{{request.user.username}}</strong> شما لایک خود را حذف کردی :(.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>')
        $(document).scrollTop(0)
        getNewInfoAboutLike()
      }
    },
    error: function (response) {
                  // alert the error if any error occured
                  console.log(response.responseJSON.errors)
              }
  })
  {% endif %}
}
</script>


{% block title %}
دانش آزاد | {{title}}
{% endblock title %}

<main id="main">
  <div id="null">

  </div>

    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>{{article.title}}</h2>
          <ol>
            <li><a href="{% url 'blog:home' %}">صفحه اصلی</a></li>
            <li><a>مقالات</a></li>
            <li>{{article.title}}</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">
        
        <div class="row">
          
          <div class="col-lg-8 entries">
            
            {% if not article.login_required %}
            <article class="entry entry-single">

              <div class="entry-img">
                <img src="{{article.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{{article.author.get_absolute_url}}">{{article.author}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time datetime="2020-01-01">{{article.jdate_cr}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">{{comments.count}} Comments</a></li>
                  <li class="d-flex align-items-center"><i class="far fa-heart"></i> <a id="like" href="#">{{article.likes.count}} Likes</a></li>
                </ul>
              </div>

              <div class="entry-content">
                {{article.text}}
              </div>

              <div class="entry-footer d-flex">
                <i class="bi bi-tags"></i>
                {% for i in article.category.all %}
                <ul class="tags">
                  <li><a href="{{i.get_absolute_url}}">{{i.title}}</a></li>
                </ul>
                {% endfor %}
            
            {% if article.likes.all %}
              {% for i in article.likes.all %}
                {% if i.user == request.user %}
                  <div style="float: left;margin-right: auto;">
                    <a onclick="Like()"><i id="ls" class="fas fa-heart"></i></a>
                  </div>
                {% endif %}
              {% endfor %}
            {% endif %}
                    <!-- <div onclick="dislikeClicked()"><i id="dislike" class="dislike fas fa-thumbs-down"></i></div> -->
            </div>

            </article><!-- End blog entry -->
            {% else %}
            <article class="entry entry-single">

              <div class="entry-img">
                <img src="{{article.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog:detail' article.slug %}">{{article.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{{article.author.get_absolute_url}}">{{article.author}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time datetime="2020-01-01">{{article.jdate_cr}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">{{comments.count}} Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <div class="text-center text-bold text-bold">
                    <h5>برای خواندن این مقاله باید ثبت نام کنید</h5>
                </div>
                <div class="col">
                  <div class="text-center">
                    <a class="btn btn-primary" href="{% url 'account:register' %}">ثبت نام</a>
                  </div>
                </div>
              </div>

              <div class="entry-footer">
                <i class="bi bi-tags"></i>
                {% for i in article.category.all %}
                <ul class="tags">
                  <li><a href="{{i.get_absolute_url}}">{{i.title}}</a></li>
                </ul>
                {% endfor %}
              </div>

            </article><!-- End blog entry -->
            {% endif %}

            <div class="blog-author d-flex align-items-center">
              {% if author.profile_pic %}
              <img src="{{author.profile_pic.url}}" class="rounded-circle float-left mx-2" alt="{{author.username}}">
              {% else %}
              <img src="{% static 'assetz/img/anony-avatar.png' %}" class="rounded-circle float-left mx-2" alt="{{author.username}}">
              {% endif %}
              <div>
                <h4>{{author.username}}</h4>
                <div class="social-links">
                    {% for i in author.contacts.all %}
                  <a href="{{i.url}}"><i class="bi bi-twitter">{{i.title}}</i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                    {% endfor %}
                </div>
                <p>
                  {{author.about}}
                </p>
              </div>
            </div><!-- End blog author bio -->

            <div class="blog-comments">
            {% if comments %}
            
            <h4 class="comments-count">{{comments.count}} نظر</h4>
            
            <div id="{{comment.pk}}" class="comment">
              {% for comment in comments %}
              <div class="d-flex">
                <!-- <div class="comment-img"><img src="assets/img/blog/comments-1.jpg" alt=""></div> -->
                  <div>
                    <h5><a href="">{{comment.from_user.username}}</a></h5>
                    <time datetime="2020-01-01">{{comment.jdate_cr}}</time>
                    <h5>{{comment.title}}</h5>
                    <p>
                        {{comment.text}}
                    </p>
                  </div>
                </div>
                {% endfor %}
              {% endif %}

              <div class="reply-form">
                <h4>نظرتو بنویس!</h4>
                <!-- <p>ایمیل شما به نمایش درنمی آید فقط برای تایید شما الزامیست </p> -->
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                  <button type="submit" class="btn btn-primary mt-2">ارسال نظر</button>

                </form>

              </div>

              </div><!-- End blog comments -->
            </div>
          <!-- </div> 
          </div> -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">جستجو</h3>
              <div class="sidebar-item s-s search-form">
                <form action="{% url 'blog:search' %}" method="POST">
                  {% csrf_token %}
                  <input type="text" name="title">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->
              <h3 class="sidebar-title">دسته بندیها</h3>
              {% if categories %}
              <div class="sidebar-item categories d-inline">
                <ul>
                  {% for i in categories %}
                    <li><a class="btn btn-primary btn-sm" href="#">{{i.title}} </a></li>
                {% endfor %}
              </ul>
            </div><!-- End sidebar categories-->
            {% endif %}


              <h3 class="sidebar-title">پست های اخیر</h3>
              {% for i in last_articles %}
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  <!-- <img src="{{i.image.url}}" alt=""> -->
                  <h4><a href="{{i.get_absolute_url}}">{{i.title}}</a></h4>
                  <time datetime="2020-01-01">{{i.jdate_cr}}</time>
                </div>
              {% endfor %}
            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->
  {% endblock %}