account/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views
from django.contrib.auth import views as _

app_name = 'account'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateUserEmailView.as_view(), name='activate'),
    path('active/again', views.SendEmailConfirmationLinkAgain.as_view(), name="active-again"),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('update/<int:pk>/', views.UpdateUserProfileView.as_view(), name='update'),
    path('delete/', views.ajax_delete_user, name='delete'),
    path('users/', views.AdministratorUsersManagerView.as_view(), name='users'),
    path('user/contacts/', views.ContactsView.as_view(), name='contacts'),
    path('dashboard/search/', views.DashboardSearchView.as_view(), name='dashboard-search'),
    path('administrator/website/system/chart/', views.ChartSystem.as_view(), name='chart'),
    path('ajax/validator/username', views.validate_username, name='validator-username'),
    path('ajax/validator/email', views.validate_email, name='validator-email'),
    path('ajax/validators/slug', views.ajax_slug_validators, name='aj-sl-val'),
    path('ajax/notification/read', views.notification_read_ajax, name='notif-read'),
    path('ajax/passwords/match', views.login_password_matches, name='validator-ps'),
    path('ajax/author/req', views.ajax_author_req, name='author-req'),
    path('contact/create/', views.CreateContactView.as_view(), name='contact-create'),
    path('contact/update/<int:pk>/', views.UpdateContactView.as_view(), name='contact-update'),
    path('contact/delete/', views.ajax_delete_user_contact, name='contact-delete'),
    path('article/create/', views.CreateArticleView.as_view(), name='article-create'),
    path('article/update/<int:pk>/', views.UpdateArticleView.as_view(), name='article-update'),
    path('article/delete/', views.ajax_delete_article, name='article-delete'),
    path('article/preview/<int:pk>/', views.DetailArticlePreView.as_view(), name='article-preview'),
    path('articles/', views.ListArticleView.as_view(), name='articles'),
    path('article/wrote/<int:pk>/', views.article_wrote, name='article-wrote'),
    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('categories/', views.CategoryAdminManagement.as_view(), name='categories'),
    path('category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category-update'),
    path('category/delete/', views.ajax_delete_category, name='category-delete'),
    path('notif/create/', views.NotificationCreator.as_view(), name='notif-create'),
    path('notifs/manage/', views.AllNotifications.as_view(), name='notifs-admin'),
    path('notif/delete/', views.ajax_delete_notifs, name="notif-delete"),
    path('message/create/', views.CreateMessage.as_view(), name="message-create"),
    path('messages/', views.MyMessages.as_view(), name='messages'),
    path('message/delete/', views.ajax_delete_messages, name='message-delete'),
    path('message/detail/<int:pk>/', views.MessageDetail.as_view(), name='message-detail'),
    path('message/update/<int:pk>/', views.MessageUpdate.as_view(), name="message-update"),
    path('comments/manage/', views.CommentManagement.as_view(), name='comments'),
    path('comments/publish/<int:pk>/', views.CommentPublisher.as_view(), name="comment-update"),
    path('comments/delete/', views.ajax_delete_comment, name='comment-delete'),
    path('user/creation/', views.AdminUserCreation.as_view(), name='user-create'),
    path('challenge/create/', views.CreateChallengeView.as_view(), name='challenge-create'),
    path('challenge/update/<int:pk>/', views.UpdateChallengeView.as_view(), name='challenge-update'),
    path('challenge/delete/', views.ajax_delete_challenges, name='challenge-delete'),
    path('challenges/', views.ChallengesView.as_view(), name='challenges'),
    path('views/', views.ViewsDetailPage.as_view(), name='views'),
    path('views/delete/', views.ajax_delete_view, name='view-delete'),
    path('views/likes/', views.LikedArticles.as_view(), name="article-likes"),
    path('article/like/delete/', views.ajax_delete_like, name='article-like-delete'),
] 

urlpatterns += [
    path('password_change/', _.PasswordChangeView.as_view(
        template_name='auth/registration/password_change.html',
        success_url=reverse_lazy('account:password_change_done')),
        name='password_change'),

    path('password_change/done/', _.PasswordChangeDoneView.as_view(
        template_name='auth/registration/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', _.PasswordResetView.as_view(
        template_name='auth/registration/password_reset.html',
        success_url=reverse_lazy('account:password_reset_done')),
        name='password_reset'),

    path('password_reset/done/', _.PasswordResetDoneView.as_view(
        template_name='auth/registration/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', _.PasswordResetConfirmView.as_view(
        template_name='auth/registration/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete')),
        name='password_reset_confirm'),

    path('reset/done/', _.PasswordResetCompleteView.as_view(
        template_name='auth/registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('authors/profiles/', views.ViewAuthorProfiles.as_view(), name='authors'),
    path('author/profile/<str:slug>/', views.ViewProfile.as_view(), name='author'),
    path('', views.HomePageView.as_view(), name='home'),
    path('posts/list/', views.ArticleListView.as_view(), name='posts'),
    path('post/detail/<str:slug>/', views.ArticleDetailView.as_view(), name='detail'),
    path('post/search/', views.SearchPageView.as_view(), name='search'),
    path('posts/category/<str:slug>/', views.CategoryRelatedToAnArticleView.as_view(), name='article-related-category'),
    path('about/', views.AboutUsPage.as_view(), name='about'),
    path('contact/', views.ContactUsPage.as_view(), name="contact"),
    path('ajax/like', views.liker, name="like"),
    path('ajax/like/update', views.send_likes_count_ajax, name="likeupdate"),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
    path('markdownx/', include( 'markdownx.urls')),
]

blog/forms.py
from .models import Comment
from django import forms


class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'title',
            'text',
        ]

blog/views.py
from blog.models import ViewsMid
from django.db.models import Q
from django.http import JsonResponse
from .forms import CommentCreationForm
from .models import Article, Category, Likes, Comment
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from django.contrib.auth.decorators import login_required
from account.models import UserProfile


# Create your views here.
class HomePageView(generic.View): 
    def get(self, request):
        posts = Article.objects.filter(published='p').order_by('-slug')[:9]
        categories = Category.objects.all()

        context = {
            'posts': posts,
            'categories': categories,
            'titlex': 'صفحه اصلی',
        }

        return render(request, 'index.html', context)


class SearchPageView(generic.View):
    def get(self, request):
        posts = Article.objects.filter(published='p').order_by('-slug')[:5]
        categories = Category.objects.all()

        return render(request, 'search.html', {'posts': posts, 'categories': categories})

    def post(self, request):
        last_posts = Article.objects.filter(published='p').order_by('-slug')[:5]
        categories = Category.objects.all()

        keyword = request.POST.get('title')
        result = Article.objects.filter(Q(title__icontains=keyword) |
                                        Q(text__icontains=keyword) |
                                        Q(slug__icontains=keyword) |
                                        Q(category__title__icontains=keyword) |
                                        Q(author__first_name__icontains=keyword) |
                                        Q(author__last_name__icontains=keyword) |
                                        Q(author__username__icontains=keyword))
        return render(request, 'search.html', {'articles': result,
                                               'posts': last_posts,
                                               'categories': categories,
                                               'title': 'نتیجه جستجو ' + f'"{keyword}"'
                                               })


class ArticleListView(generic.ListView): 
    paginate_by = 9
    queryset = Article.objects.filter(published='p')
    model = Article
    template_name = 'articles.html'
    context_object_name = 'articles'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Article.objects.filter(published='p').order_by('-slug')[:9]
        categories = Category.objects.all()

        context['posts'] = posts
        context['categories'] = categories
        context['title'] = 'مقالات'
        return context


class ArticleDetailView(generic.View):
    def get(self, request, slug):
        comment_form = CommentCreationForm()
        article = get_object_or_404(Article, published='p', slug=slug)
        categories = Category.objects.all()[:5]
        latest_articles = Article.objects.filter(published='p')[:5]
        comments = Comment.objects.filter(to_article=article.pk, published=True)
        articles = Article.objects.all()[:5]
        try:
            user_ip = ViewsMid.objects.get(ip_addr=request.user.ip_address)
        except ViewsMid.DoesNotExist:
            user_ip = ViewsMid.objects.create(ip_addr=request.user.ip_address, ua=request.user.ua, user=request.user)
        
        view = article.hits.count()
        author = article.author

        context = {
            'form': comment_form,
            'article': article,
            'view': view,
            'comments': comments,
            'author': author,
            'categories': categories,
            'last_articles': latest_articles,
            'posts': articles,
            'title': article.title
        }
        return render(request, 'article.html', context)

    def post(self, request, slug):
        article = Article.objects.get(published='p', slug=slug)
        form = CommentCreationForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.from_user = request.user
            comment.to_article = article
            comment.published = False
            comment.save()

            return redirect('account:comments')


class CategoryRelatedToAnArticleView(generic.ListView): 
    model = Article
    context_object_name = 'articles'
    template_name = 'category.html'

    def get_queryset(self):
        return Article.objects.filter(category__slug=self.kwargs['slug'], published='p')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Article.objects.filter(published='p').order_by('-slug')[:9]
        categories = Category.objects.all()

        context['posts'] = posts
        context['categories'] = categories
        context['title'] = Category.objects.get(slug=self.kwargs['slug']).title
        return context


class ViewProfile(generic.DetailView):
    model = UserProfile
    context_object_name = 'author'
    slug_field = 'username'
    template_name = 'author.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Article.objects.filter(published='p').order_by('-slug')[:9]
        categories = Category.objects.all()

        context['posts'] = posts
        context['categories'] = categories
        context['title'] = 'مشاهده پروفایل'
        return context


class ViewAuthorProfiles(generic.ListView): 
    model = UserProfile
    context_object_name = 'authors'
    queryset = UserProfile.objects.filter(is_author=True)
    template_name = 'authors.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Article.objects.filter(published='p').order_by('-slug')[:9]
        categories = Category.objects.all()

        context['posts'] = posts
        context['categories'] = categories
        context['title'] = 'نویسندگان'
        return context
    

class Challenges(generic.View):
    def get(self, request):
        posts = Article.objects.filter(published='p').order_by('-slug')[:9]
        categories = Category.objects.all()
        context = {}
        context['posts'] = posts
        context['categories'] = categories
        context['title'] = 'چالش ها'
        return render(request, 'challenge.html', context)


class AboutUsPage(generic.View):
    def get(self, request):
        context = {
            'categories': Category.objects.all()[:5],
            'posts': Article.objects.all()[:5],
            'title': 'درباره'
        }
        return render(request, 'about.html', context)


class ContactUsPage(generic.View):
    def get(self, request):
        context = {
            'categories': Category.objects.all()[:5],
            'posts': Article.objects.all()[:5],
            'title': 'ارتباط'
        }
        return render(request, 'contact.html', context)


@login_required
def liker(request):
    if request.method == "POST" and request.is_ajax:
        pk = request.POST.get("id")
        post = Article.objects.get(pk=pk)
        try:
            like = Likes.objects.get(user=request.user, post=post)
            like.delete()
            return JsonResponse({
                'disliked': True
            })
        except Likes.DoesNotExist:
            Likes.objects.create(user=request.user, post=post)
            return JsonResponse({
                'liked': True
            })


def send_likes_count_ajax(request):
    if request.is_ajax and request.method == "POST":
        pk = request.POST.get("wal")
        try:
            article = Article.objects.get(pk=pk)
            return JsonResponse({
                "likes": article.likes.count()
            })
        except Article.DoesNotExist:
            return JsonResponse({
                "Error": 503
            })

blog/templates/base_blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<style>
  .s-s{
    direction: ltr;
  }
    
    
@media only screen and (max-width: 900px) {
  .manage-user-li{
    display: flex;
  }
}
</style>


<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
<title>
  {% block title %}
  {% endblock %}
</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <script src="{% static 'assets/js/jquery.js' %}"></script>
  <!-- Favicons -->
  <link href="{% static 'assetz/css/icofont/icofont.min.css' %}" rel="stylesheet">
  <link href="assetz/img/favicon.png" rel="icon">
  <link href="assetz/img/apple-touch-icon.png" rel="apple-touch-icon">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assetz/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assetz/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assetz/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assetz/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assetz/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assetz/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assetz/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'assetz/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna - v4.3.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->


</head>

<body class="rtl">

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center header-transparent">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1 class="text-light"><a href="{% url 'blog:home' %}"><span>دانش آزاد</span></a></h1>
        <!-- <a href="index.html"><img src="assetz/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="active" href="{% url 'blog:home' %}">صفحه اصلی</a></li>
          <li><a href="{% url 'blog:posts' %}"><span>مقالات</span> </a></li>
          <li><a href="{% url 'blog:authors' %}">نویسندگان</a></li>
          <li><a href="{% url 'blog:contact' %}">ارتباط</a></li>
          <li><a href="{% url 'blog:about' %}">درباره</a></li>
          {% if not user.is_authenticated %}
          <li class="manage-user-li"><a href="{% url 'account:register' %}"><i class="fas fa-user-plus"></i> ثبت نام</a></li>
          <li class="manage-user-li"><a href="{% url 'account:login' %}"><i class="fas fa-door-open"></i> ورود </a></li>
          {% else %}
          <li class="manage-user-li"><a href="{% url 'account:logout' %}"><i class="fas fa-sign-out-alt"></i> خارج شدن </a></li>
          <li class="manage-user-li"><a href="{% url 'account:dashboard' %}"><i class="fas fa-home"></i> داشبورد</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block content %}
  {% endblock %}

  
  <!-- ======= Footer ======= -->
  <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>لینکها</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">صفحه اصلی</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">مقالات</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">درباره</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">ارتباط</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">نویسندگان</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>دسته بندیها</h4>
            {% for category in categories %}
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{{category.get_absolute_url}}">{{category.title}}</a></li>

            </ul>
            {% endfor %}
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>ارتباط با ما</h4>
            <p>
              <!-- A108 Adam Street <br> -->
              <!-- New York, NY 535022<br> -->
              <!-- United States <br><br> -->
              <strong>Telegram:</strong> <a href="https://t.me/FreeKnowledgeOfficial">@FreeKnowledgeOfficial</a><br>
              <strong>Github:</strong><a href="https://github.com/DrM0h4MM4d"> DrM0h4MM4d</a><br>
              <strong>Email:</strong><a href="mailto:freeknwoledgeofficial@gmail.com">freeknowledgemail</a><br>
            </p>

          </div>

          <div class="col-lg-3 col-md-6 footer-info">
            <h3> درباره ما</h3>
            <p>وبسایت ما تلاش بر پیشرفت سواد تکنولوژی در بین مردم خوب کشورمان را دارد و خواستار آینده ای بهتر و قدرتمند برای کشور عزیزمان است.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="https://t.me/FreeKnowledgeOfficial" class="telegram"><i class="bx bxl-telegram"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; تمامی حقوق متعلق به <strong><span>همین وبسایت</span></strong> است. 
      </div>
      <div class="credits">
        فارسی سازی و بهینه شده توسط ادمین
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assetz/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assetz/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assetz/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assetz/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assetz/vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'assetz/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assetz/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assetz/vendor/waypoints/noframework.waypoints.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assetz/js/main.js' %}"></script>

</body>

</html>