account/urls.py
from django.urls import path
from django.urls.base import reverse_lazy
from . import views
from django.contrib.auth import views as _

app_name = 'account'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', views.ActivateUserEmailView.as_view(), name='activate'),
    path('active/again', views.SendEmailConfirmationLinkAgain.as_view(), name="active-again"),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('update/<int:pk>/', views.UpdateUserProfileView.as_view(), name='update'),
    path('delete/', views.ajax_delete_user, name='delete'),
    path('users/', views.AdministratorUsersManagerView.as_view(), name='users'),
    path('user/contacts/', views.ContactsView.as_view(), name='contacts'),
    path('dashboard/search/', views.DashboardSearchView.as_view(), name='dashboard-search'),
    path('administrator/website/system/chart/', views.ChartSystem.as_view(), name='chart'),
    path('ajax/validator/username', views.validate_username, name='validator-username'),
    path('ajax/validator/email', views.validate_email, name='validator-email'),
    path('ajax/validators/slug', views.ajax_slug_validators, name='aj-sl-val'),
    path('ajax/notification/read', views.notification_read_ajax, name='notif-read'),
    path('ajax/passwords/match', views.login_password_matches, name='validator-ps'),
    path('ajax/author/req', views.ajax_author_req, name='author-req'),
    path('contact/create/', views.CreateContactView.as_view(), name='contact-create'),
    path('contact/update/<int:pk>/', views.UpdateContactView.as_view(), name='contact-update'),
    path('contact/delete/', views.ajax_delete_user_contact, name='contact-delete'),
    path('article/create/', views.CreateArticleView.as_view(), name='article-create'),
    path('article/update/<int:pk>/', views.UpdateArticleView.as_view(), name='article-update'),
    path('article/delete/', views.ajax_delete_article, name='article-delete'),
    path('article/preview/<int:pk>/', views.DetailArticlePreView.as_view(), name='article-preview'),
    path('articles/', views.ListArticleView.as_view(), name='articles'),
    path('article/wrote/<int:pk>/', views.article_wrote, name='article-wrote'),
    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('categories/', views.CategoryAdminManagement.as_view(), name='categories'),
    path('category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category-update'),
    path('category/delete/', views.ajax_delete_category, name='category-delete'),
    path('notif/create/', views.NotificationCreator.as_view(), name='notif-create'),
    path('notifs/manage/', views.AllNotifications.as_view(), name='notifs-admin'),
    path('notif/delete/', views.ajax_delete_notifs, name="notif-delete"),
    path('message/create/', views.CreateMessage.as_view(), name="message-create"),
    path('messages/', views.MyMessages.as_view(), name='messages'),
    path('message/delete/', views.ajax_delete_messages, name='message-delete'),
    path('message/detail/<int:pk>/', views.MessageDetail.as_view(), name='message-detail'),
    path('message/update/<int:pk>/', views.MessageUpdate.as_view(), name="message-update"),
    path('comments/manage/', views.CommentManagement.as_view(), name='comments'),
    path('comments/publish/<int:pk>/', views.CommentPublisher.as_view(), name="comment-update"),
    path('comments/delete/', views.ajax_delete_comment, name='comment-delete'),
    path('user/creation/', views.AdminUserCreation.as_view(), name='user-create'),
    path('challenge/create/', views.CreateChallengeView.as_view(), name='challenge-create'),
    path('challenge/update/<int:pk>/', views.UpdateChallengeView.as_view(), name='challenge-update'),
    path('challenge/delete/', views.ajax_delete_challenges, name='challenge-delete'),
    path('challenges/', views.ChallengesView.as_view(), name='challenges'),
    path('views/', views.ViewsDetailPage.as_view(), name='views'),
    path('views/delete/', views.ajax_delete_view, name='view-delete'),
    path('views/likes/', views.LikedArticles.as_view(), name="article-likes"),
    path('article/like/delete/', views.ajax_delete_like, name='article-like-delete'),
] 

urlpatterns += [
    path('password_change/', _.PasswordChangeView.as_view(
        template_name='auth/registration/password_change.html',
        success_url=reverse_lazy('account:password_change_done')),
        name='password_change'),

    path('password_change/done/', _.PasswordChangeDoneView.as_view(
        template_name='auth/registration/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', _.PasswordResetView.as_view(
        template_name='auth/registration/password_reset.html',
        success_url=reverse_lazy('account:password_reset_done')),
        name='password_reset'),

    path('password_reset/done/', _.PasswordResetDoneView.as_view(
        template_name='auth/registration/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', _.PasswordResetConfirmView.as_view(
        template_name='auth/registration/password_reset_confirm.html',
        success_url=reverse_lazy('account:password_reset_complete')),
        name='password_reset_confirm'),

    path('reset/done/', _.PasswordResetCompleteView.as_view(
        template_name='auth/registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('authors/profiles/', views.ViewAuthorProfiles.as_view(), name='authors'),
    path('author/profile/<str:slug>/', views.ViewProfile.as_view(), name='author'),
    path('', views.HomePageView.as_view(), name='home'),
    path('posts/list/', views.ArticleListView.as_view(), name='posts'),
    path('post/detail/<str:slug>/', views.ArticleDetailView.as_view(), name='detail'),
    path('post/search/', views.SearchPageView.as_view(), name='search'),
    path('posts/category/<str:slug>/', views.CategoryRelatedToAnArticleView.as_view(), name='article-related-category'),
    path('about/', views.AboutUsPage.as_view(), name='about'),
    path('contact/', views.ContactUsPage.as_view(), name="contact"),
    path('ajax/like', views.liker, name="like"),
    path('ajax/like/update', views.send_likes_count_ajax, name="likeupdate"),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
    path('markdownx/', include( 'markdownx.urls')),
]

account/views.py
from extensions.bot_send_to_channel import send_to_channel
from django.db.models import Q
from .utils import check_email_spam
import re
from django.db.models import Count
from django.template.loader import render_to_string
from django.contrib.auth.forms import UserCreationForm
from django.http.response import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from datetime import timedelta, datetime
from .tasks import send_email
from .models import (
    ChallengeEvent,
    ContactsUser,
    Message,
    NotificationAdminCenter,
    UserProfile
)
from django.contrib.auth import (
    get_user_model,
    login,
    logout,
    update_session_auth_hash,
    authenticate
)
from .forms import (
    AgainEmailConfirmationForm,
    CreateArticleForm,
    CreateUserContactsForm,
    MessageForm,
    NotificationCreatorForm,
    UpdateUserArticleForm,
    UpdateUserAccountForm,
    UpdateUserContactsForm,
    UserLoginForm,
    UserRegistrationForm,
    UserSetPassword
)
from .mixins import (
    ArticleCreateFormMixin,
    ArticlePreviewMixin,
    ContactCreateFormMixin,
    IsArticleCreatorOr404Mixin,
    IsAuthorOrSuperUserOr404,
    IsContactCreatorOr404Mixin,
    IsSelfOr404Mixin,
    SuperUserMixinRequired
)
from blog.models import (
    Article,
    Comment,
    Category,
    ViewsMid,
    Likes,
)

User = get_user_model()


# Create your views here.
class UserLoginView(generic.View):

    def get(self, request):
        form = UserLoginForm()
        return render(request, 'auth/registration/login.html', {'form': form})
    
    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            remember_me = form.cleaned_data.get('remember_me')
            if not remember_me:
                request.session.set_expiry(0)

            user = authenticate(username=username, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(message="عزیز {}, شما وارد اکانتتان شدید!", request=request)
                return redirect("account:dashboard")
            else:
                # return HttpResponse("User Does Not Exists")
                return render(request, 'auth/registration/login.html',
                              {'error': 'کاربری با این مشخصات وجود ندارد', 'form': form})
        else:
            return render(request, 'auth/registration/login.html', {'form': form})


class LogoutView(generic.View):

    def get(self, request):
        logout(request)
        messages.success(message="شما از اکانتتان خارج شدید!", request=request)
        return redirect('blog:home')


class UserRegistrationView(generic.View):

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            username, email = form.cleaned_data.get("username"), form.cleaned_data.get("email")
            if UserProfile.objects.filter(Q(username=username) | Q(email=email)).exists():
                return HttpResponse("اکانتی با این مشخصات وجود دارد")
            else:
                user = UserProfile.objects.create(username=username, email=email, is_active=False)
            if check_email_spam(email):
                current_site = get_current_site(request)
                mail_subject = 'اکانت خود را تایید کنید.'
                message = render_to_string('auth/acc_active_email.html', {
                        'user': user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': account_activation_token.make_token(user),
                    })
                to_email = email
                send_email.delay(mail_subject, message, to_email)
                return HttpResponse("ایمیل خود را تایید کنید")
            else:
                return HttpResponse("""ما قبلا به شما ایمیل ارسال کردیم،"
                                    برای جلوگیری از اسپم لطفا 3 دقیقه صبر کنید و. دوباره تلاش کنید.""")
        else:
            return HttpResponse("فرم اشتباه پر شده است")

    def get(self, request):
        form = UserRegistrationForm()
        return render(request, 'auth/register.html', {'form': form})


class SendEmailConfirmationLinkAgain(generic.View):
    def get(self, request):
        form = AgainEmailConfirmationForm()
        return render(request, 'auth/again_email_activation.html', {'form': form})
            
    def post(self, request):
        form = AgainEmailConfirmationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            try:
                user = UserProfile.objects.get(email=email)
                if not user.password:
                    if check_email_spam(email):
                        current_site = get_current_site(request)
                        mail_subject = 'اکانت خود را تایید کنید.'
                        message = render_to_string('auth/acc_active_email.html', {
                            'user': user,
                            'domain': current_site.domain,
                            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                            'token': account_activation_token.make_token(user),
                        })
                        to_email = form.cleaned_data.get('email')
                        send_email.delay(mail_subject, message, to_email)
                        return HttpResponse('لطفا ایمیل خود را تایید کنید.')
                    else:
                        return HttpResponse("ما قبلا به شما ایمیل ارسال کردیم، برای جلوگیری از اسپم لطفا 3 دقیقه صبر کنید و. دوباره تلاش کنید.")
                else:
                    return HttpResponse("پسورد برای شما ثبت شده است.")
            except UserProfile.DoesNotExist:
                return HttpResponse("اکانت شما وجود ندارد!")


class ActivateUserEmailView(generic.View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            # activate user and login:
            user.is_active = True
            user.save()
            login(request, user)
            
            form = UserSetPassword()
            return render(request, 'auth/activation_complete.html', {'form': form})
            
        else:
            return HttpResponse('لینک منقضی شده است!')
            
    def post(self, request, uidb64, token):

        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        # form = PasswordResetForm(request.POST)
        form = UserSetPassword(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=user.pk)
            # user.set_password(form.cleaned_data.get("raw_password"))
            raw_password = form.cleaned_data.get("raw_password")
            user.set_password(raw_password)
            user.save()
            update_session_auth_hash(request, user)
            return redirect('account:dashboard')
        else:
            return render(request, 'auth/activation_complete.html', {'form': UserSetPassword()})


class DashboardView(LoginRequiredMixin, generic.View):
    login_url = 'account:login'
    
    def get(self, request):
        user = get_object_or_404(UserProfile, pk=request.user.pk)
        challenge = ChallengeEvent.objects.last()
        challenge_count = ChallengeEvent.objects.count()
        views_count = ViewsMid.objects.count()
        last_mounth = datetime.today() - timedelta(days=30)
        today = datetime.today()
        last_week = datetime.today() - timedelta(days=7)
        mounth_views_count = Article.objects.filter(published='p').annotate(
            count=Count("hits", filter=Q(articlehit__date_cr__gt=last_mounth))
        ).count()
        week_views_count = Article.objects.filter(published='p').annotate(
            count=Count("hits", filter=Q(articlehit__date_cr__gt=last_week))
        ).count()
        today_views_count = Article.objects.filter(published='p').annotate(
            count=Count("hits", filter=Q(articlehit__date_cr=today))
        ).count()
        articles_count = Article.objects.count()
        authors = UserProfile.objects.filter(is_author=True).count()
        admins = UserProfile.objects.filter(is_superuser=True).count()
        users = UserProfile.objects.filter(is_author=False, is_superuser=False, is_active=True).count()
        if self.request.user.is_superuser:
            articles = Article.objects.order_by("-title")[:5]
        elif self.request.user.is_author:
            articles = Article.objects.filter(author=self.request.user)
        elif not self.request.user.is_superuser and not self.request.user.is_author and \
                self.request.user.is_authenticated and self.request.user.is_active:
            articles = []
            article = Article.objects.all()
            for i in article:
                for x in i.likes.all():
                    if x.user == self.request.user:

account/templates/users/admin-chart-system.html
{% extends 'base/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<script>
    var ac = '{{ac}}';
    var vc = '{{vc}}';
    var uc = '{{uc}}';
    var pc = '{{pc}}';
</script>



<div class="main-panel">
    <div class="content-wrapper">
      <div id="msg"></div>
      <div class="page-header">
        <h3 class="page-title"> سیستم آمار وبسایت </h3>
        <nav aria-label="breadcrumb" dir="ltr" class="text-right">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">داشبورد</a></li>
            <li class="breadcrumb-item active" aria-current="page">سیستم آمار</li>
          </ol>
        </nav>
      </div>
      <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">سیستم آمار</h4>
             <canvas id="barChart" style="height:300px"></canvas>
             
             <!-- <canvas id="lineChart" style="height: 231px; display: block; width: 462px;" width="462" height="231" class="chartjs-render-monitor"></canvas> -->
          </div>
        </div>
      </div>


      <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
      <script src="{% static 'assets/js/chart.js' %}"></script>
      <script src="{% static 'assets/js/off-canvas.js' %}"></script>
      <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
      <script src="{% static 'assets/js/misc.js' %}"></script>
      <script src="{% static 'assets/js/settings.js' %}"></script>
      <script src="{% static 'assets/js/todolist.js' %}"></script>
      <!-- <script src="{% static 'assets/js/chart.js' %}"></script> -->


      {% endblock %}

account/templates/users/admin-user-contacts.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}


<script>

  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
  
  
      function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
  
  function clickKon(pk){
      console.log("Hi")
      window._id = pk;
      $("#exampleModal").modal('show');
  }
  
  $(document).ready(function(){
    $("#delete").click(()=>{
        $.ajax({
            url: "{% url 'account:contact-delete' %}",
            method: "post",
            headers: {"X-CsrfToken": getCookie('csrftoken')},
            data: {'id': window._id},
            success: async function(response){
                if (response.success){
                    
                  var eleid = parseInt(window._id);
                  // $(`#${eleid}`).css({'display': 'none'})  
                  $(`#${eleid}`).hide('2000');
  
                    $("#exampleModal").modal('hide');
                    $("#msg").addClass('alert alert-success').text('راه ارتباطی موردنظر حذف شد.')
                    $(document).scrollTop();
                    await sleep(5000);
                    $("#msg").removeClass('alert alert-danger').text('')
                }
                else if (response.permissionError){
                    $('#exampleModal').modal('hide');
                    $('#msg').addClass('alert alert-danger').text('این راه ارتباطی متعلق به شما نیست!')
                }
            }
        })
    })
  });
  
  </script>
  

<!-- aria-labelledby="exampleModalLabel" aria-hidden="true" -->
  
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">مطمئنی میخوای این راه ارتباطی رو حذف کنی؟</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          اگه حذفش کنی دیگه نمیتونی برش گردونی دوست عزیز!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">لغو</button>
        <button type="button" class="btn btn-danger" id="delete">حذف</button>
      </div>
    </div>
  </div>
</div>


<div class="main-panel">
    <div class="content-wrapper">
      <div id="msg"></div>
      <div class="page-header">
        <h3 class="page-title"> شبکه های اجتماعی {{user.usename}} </h3>
        <nav aria-label="breadcrumb" dir="ltr" class="text-right">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">داشبورد</a></li>
            <li class="breadcrumb-item active" aria-current="page">شبکه های احتماعی من </li>
          </ol>
        </nav>
      </div>
      <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">راه ارتباطی ساخته شده</h4>
            <p class="card-description"> همه راه های ارتباطی من 
            </p>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th> # </th>
                            <th> نام شبکه اجتماعی </th>
                            <th> آدرس شبکه اجتماعی  </th>
                            <th>تاریخ</th>    
                            <th>
                                بررسی راه ارتباطی
                            </th>
                        
                        </tr>
                    </thead>
                    <tbody>
                {% for i in contacts %}
                  <tr id="{{i.pk}}">
                      <td>{{ i.pk }}</td>
                    <td> {{i.title}} </td>
                    <td>{{i.jdate_cr}}</td>
                    <!-- <td> -->
                      <!-- <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                      </div> -->
                    <!-- </td> -->
                    <td>{{ i.url }}</td>
                    <!-- <td>{{i.expr_date}} -->
                    <!-- </td> -->
                    <td>
                        <div class="text-center">
                            <a class="btn btn-sm btn-primary" href="{% url 'account:article-update' i.pk %}">ویرایش </a>
                            <button type="button" onclick="clickKon('{{i.pk}}');" class="btn btn-danger btn-sm" value="{{i.pk}}" id="myBtn">حذف</button>
                            <!-- <a class="btn btn-sm btn-success" href="{% url 'account:article-preview' i.pk %}">پیش نمایش </a> -->
                        </div>
                    </td>
                  </tr>
                  {% empty %}
                  <p class="text-bold text-danger text-center">هنوز راه ارتباطی وجود ندارد.</p>
                  {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}

account/templates/users/admin-user-management.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<script>




  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
  
  
      function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
  
  function clickKon(pk){
      console.log("Hi")
      window._id = pk;
      $("#exampleModal").modal('show');
  }
  
  $(document).ready(function(){
    $("#delete").click(()=>{
        $.ajax({
            url: "{% url 'account:delete' %}",
            method: "post",
            headers: {"X-CsrfToken": getCookie('csrftoken')},
            data: {'id': window._id},
            success: async function(response){
                if (response.success){
                    
                  var eleid = parseInt(window._id);
                  // $(`#${eleid}`).css({'display': 'none'})  
                  $(`#${eleid}`).hide('2000');
  
                    $("#exampleModal").modal('hide');
                    $("#msg").addClass('alert alert-success').text('اکانت موردنظر حذف شد.')
                    $(document).scrollTop();
                    await sleep(5000);
                    $("#msg").removeClass('alert alert-danger').text('')
                }
                else if (response.permissionError){
                    $('#exampleModal').modal('hide');
                    $('#msg').addClass('alert alert-danger').text('این اکانت متعلق به شما نیست!')
                }
            }
        })
    })
  });
  
  </script>
  

<!-- aria-labelledby="exampleModalLabel" aria-hidden="true" -->
  
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">مطمئنی میخوای این اکانت رو حذف کنی؟</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          اگه حذفش کنی دیگه نمیتونی برش گردونی دوست عزیز!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">لغو</button>
        <button type="button" class="btn btn-danger" id="delete">حذف</button>
      </div>
    </div>
  </div>
</div>




<div class="main-panel">
    <div class="content-wrapper">
      <div id="msg">

      </div>
      <div class="page-header">
        <h3 class="page-title"> کاربران </h3>
        <nav aria-label="breadcrumb" dir="ltr" class="text-right">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">داشبورد</a></li>
            <li class="breadcrumb-item active" aria-current="page">همه کاربران </li>
          </ol>
        </nav>
      </div>
      <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"> کاربران</h4>
            <p class="card-description"> همه کاربران
            </p>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th> # </th>
                            <th> نام </th>
                            <th> نام خانوادگی   </th>
                            <th> نام کاربری </th>
                            <th> ایمیل </th>
                            <th> شماره تلقن </th>
                            <th> درباره کوتاه </th>
                            <th> درباره </th>
                            <th> وضعیت ارسال پیام </th>
                            <th> وضعیت نویسندگی </th>
                            <th> تاریخ وارد شدن </th>
                            <td>
                                بررسی کاربر
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                {% for i in users %}
                  <tr id="{{i.pk}}">
                    {% if i.profile_pic %}
                    <td><img src="{{i.profile_pic.url}}"></td>
                    {% else %}
                    <td>عکس وجود ندارد</td>
                    {% endif %}
                    <td>{{ i.first_name }}</td>
                    <td> {{i.last_name}} </td>
                    <td>{{i.username}}</td>
                    <td>{{ i.email }}</td>
                    <td>{{i.phone}}</td>
                    <td>{{i.short_about}}</td>
                    <td>{{i.about}}</td>
                    <td>{{i.can_send_message}}</td>
                    <td>{{i.is_author}}</td>
                    <td>{{i.last_login}}</td>
                    <!-- <td> -->
                      <!-- <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                      </div> -->
                    <!-- </td> -->
                    <td>
                        <div class="text-center">
                            <a class="btn btn-sm btn-primary" href="{% url 'account:update' i.pk %}">ویرایش </a>
                            <button type="button" onclick="clickKon('{{i.pk}}');" class="btn btn-danger btn-sm" value="{{i.pk}}" id="myBtn">حذف</button>
                            <!-- <a class="btn btn-sm btn-success" href="{% url 'account:article-preview' i.pk %}">پیش نمایش </a> -->
                        </div>
                    </td>
                  </tr>
                  {% empty %}
                  <p class="text-bold text-danger text-center">هنوز کاربری وجود ندارد.</p>
                  {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}